spring:
  application:
    name: eureka-server
  cloud:
    bootstrap:
      enabled: true
  jmx:
    port: 9001
  output:
    ansi:
      enabled: ALWAYS

server:
  port: 8070

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5
